camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
btc:
  send-btc-cli-command-pattern: /usr/local/bin/docker exec minimal-crypto-exchange_node_1 bitcoin-cli sendtoaddress %s %.9f
accounts:
  btc:
    exchange:
      address: '2N1akcbAa3oXJ7RNxrAWmL7ZuuU9iHg9tpG'
      private-key: ''
  eth:
    exchange:
      address: '0x190FD61ED8fE0067f0f09EA992C1BF96209bab66'
      private-key: b07aedf303f832664eb7a5295be737776cb1ad17a277ec287b3b3c7bac154e5e
      password: a-turkey-is-a-chicken-designed-by-a-committee
    usdt:
      contract-address: '0xa682a5972D1A8175E2431B26586F486bBa161A11'
networks:
  eth:
    url: http://localhost:8178