camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
accounts:
  btc:
    exchange:
      address: '2N1akcbAa3oXJ7RNxrAWmL7ZuuU9iHg9tpG'
  eth:
    exchange:
      address: '0x190FD61ED8fE0067f0f09EA992C1BF96209bab66'
      private-key: b07aedf303f832664eb7a5295be737776cb1ad17a277ec287b3b3c7bac154e5e
      password: a-turkey-is-a-chicken-designed-by-a-committee
    usdt:
      contract-address: '0xB1B28aD1b852AecB9aB7CA47CA7E7460Eb8C501F'
networks:
  eth:
    url: http://localhost:8178