camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  filter:
    create: All tasks
accounts:
  btc:
    exchange:
      address: '2N1akcbAa3oXJ7RNxrAWmL7ZuuU9iHg9tpG'
  eth:
    exchange:
      address: '0x190FD61ED8fE0067f0f09EA992C1BF96209bab66'
      private-key: b07aedf303f832664eb7a5295be737776cb1ad17a277ec287b3b3c7bac154e5e
      password: a-turkey-is-a-chicken-designed-by-a-committee
    usdt:
      buffer-address: '0x411167FeFecAD12Da17F9063143706C39528aa28'
      contract-address: '0x86c58D398fF7EF4cA13BdD216D0973f37fA0D25b'
networks:
  eth:
    url: http://localhost:8178